server:
  port: 8080
  servlet:
    session:
      timeout: 1800
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: text/html,text/xml,text/javascript,text/css,text/plain,application/javascript,application/json
spring:
  datasource:
    username: root
    password: 442abc
    url: jdbc:mysql://wangzhiwang.online:3306/houseweb2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB


  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8

  resources:
    static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: hnu.houseweb.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

filePath:
  basePath:/var/www/html/houseweb